[package]
name = "gc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dst-init = "0.4.0"
rand = "0.8.5"
gc-derive={path="gc-derive"}
paste = "1.0.12"
peg = "0.8.1"